// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/files"
import "github.com/swaggo/gin-swagger"

const docTemplate = `{
  "schemes": ["http"],
  "swagger": "2.0",
  "info": {
    "description": "A complete REST API for managing todos using Go and Gin",
    "title": "Todo API",
    "version": "1.0"
  },
  "host": "localhost:8082",
  "basePath": "/api/v1",
  "paths": {
    "/todos": {
      "get": {
        "description": "Retrieves a list of all todos from the database",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["todos"],
        "summary": "Get all todos",
        "responses": {
          "200": {
            "description": "List of todos",
            "schema": {
              "type": "array"
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "description": "Creates a new todo with the provided title and description",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["todos"],
        "summary": "Create a new todo",
        "parameters": [
          {
            "description": "Todo data",
            "name": "todo",
            "in": "body",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Todo created successfully"
          },
          "400": {
            "description": "Invalid request body or validation error"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/todos/{id}": {
      "get": {
        "description": "Retrieves a specific todo by its ID",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["todos"],
        "summary": "Get todo by ID",
        "parameters": [
          {
            "type": "integer",
            "description": "Todo ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Todo details"
          },
          "400": {
            "description": "Invalid ID format"
          },
          "404": {
            "description": "Todo not found"
          }
        }
      },
      "put": {
        "description": "Updates an existing todo with the provided ID",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["todos"],
        "summary": "Update a todo",
        "parameters": [
          {
            "type": "integer",
            "description": "Todo ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Updated todo data",
            "name": "todo",
            "in": "body",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Todo updated successfully"
          },
          "400": {
            "description": "Invalid ID format or request body"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "delete": {
        "description": "Deletes an existing todo by its ID",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["todos"],
        "summary": "Delete a todo",
        "parameters": [
          {
            "type": "integer",
            "description": "Todo ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Todo deleted successfully"
          },
          "400": {
            "description": "Invalid ID format"
          },
          "404": {
            "description": "Todo not found"
          }
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
type SwaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfoInstance is the global variable that stores the Swagger configuration
var SwaggerInfoInstance = SwaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8082",
	BasePath:    "/api/v1",
	Schemes:     []string{"http"},
	Title:       "Todo API",
	Description: "A complete REST API for managing todos using Go and Gin",
}

func init() {
	swag.Register(Name, &Spec)
}
